services:
  vrising:
    build: .
    container_name: vrising
    network_mode: bridge
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "${SERVER_DIR}:/mnt/vrising/server"
      - "${DATA_DIR}:/mnt/vrising/data"
      - "${SETTINGS_DIR}:/mnt/vrising/settings"
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
