services:
  vrising:
    build: .
    container_name: vrising
    network_mode: bridge
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "./server:/mnt/vrising/server"
      - "./data:/mnt/vrising/data"
      - "./settings:/mnt/vrising/settings"
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
