version: "3.3"
services:
  vrising:
    build: .
    container_name: vrising
    network_mode: bridge
    environment:
      - TZ=Europe/Berlin
      - SERVER_NAME=[DE/EN] Zur Weltenesche|x3|TP+Items|No Wipes|PVP
      - WORLD_NAME=yggdrasil
    volumes:
      - "./server:/mnt/vrising/server:rw"
      - "./data:/mnt/vrising/data:rw"
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
